version: '3'
services:
  tomcat-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: wilmar-user-web
    container_name: user-web
    volumes:
      - E:/99.Jobs/01.Wilmar/98.docker/00.logs/:/usr/local/tomcat/logs
    ports:
      - "8081:8080"
    networks:
      - my-network

volumes:
  my-volume:
networks:
  my-network: